DROP USER admin;
DROP USER gestor;
DROP USER cliente;
DROP USER invitado;


CREATE USER admin WITH PASSWORD 'admin' SUPERUSER CREATEDB CREATEROLE;

CREATE USER gestor WITH PASSWORD 'gestor';
GRANT INSERT, SELECT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO GESTOR;
REVOKE CREATE ON SCHEMA public FROM GESTOR;

CREATE USER cliente WITH PASSWORD 'cliente';
GRANT INSERT,SELECT ON Usuario_tiene_edicion TO CLIENTE;
GRANT INSERT,SELECT ON Usuario_desea_disco TO CLIENTE;

CREATE USER invitado;
GRANT SELECT ON Grupofinal TO CLIENTE;
GRANT SELECT ON Discofinal TO CLIENTE;
GRANT SELECT ON Cancionesfinal TO CLIENTE;